version: '3'

services:

  redis:
      image: redis
      ports:
        - '6379:6379'

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8000"
    volumes:
      - .:/habit
      - ./static:/app/static
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  celery:
    restart: always
    build: .
    command: celery -A config worker —loglevel=info && celery -A config beat —loglevel=info
    volumes:
      - .:/app
    depends_on:
      - app
      - redis

volumes:
  pg_data:
  static: