# Generated by Django 4.2.5 on 2023-09-13 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=150, verbose_name='Место')),
                ('time', models.TimeField(verbose_name='Время')),
                ('action', models.CharField(max_length=150, unique=True, verbose_name='Действие')),
                ('duration', models.PositiveIntegerField(default=120, verbose_name='Длительность выполнения, с')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публичности привычки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
            ],
        ),
        migrations.CreateModel(
            name='PleasantHabit',
            fields=[
                ('habit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habit.habit')),
                ('is_pleasant_habit', models.BooleanField(default=True, verbose_name='Признак приятной привычки')),
            ],
            options={
                'verbose_name': 'Приятная привычка',
                'verbose_name_plural': 'Приятные привычки',
            },
            bases=('habit.habit',),
        ),
        migrations.CreateModel(
            name='UnpleasantHabit',
            fields=[
                ('habit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='habit.habit')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('frequency', models.CharField(choices=[('EVERY DAY', 'раз в день'), ('EVERY OTHER DAY', 'через день'), ('EVERY WEEK', 'раз в неделю')], default='EVERY DAY', max_length=100, verbose_name='Периодичность')),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.pleasanthabit', verbose_name='Приятная привычка')),
            ],
            options={
                'verbose_name': 'Неприятная привычка',
                'verbose_name_plural': 'Неприятные привычки',
            },
            bases=('habit.habit',),
        ),
    ]
